### ISSUE TITLE
Can't drop tabs between panels (and some other issues with v4)

### ISSUE THREAD

**Issue by artaommahe** [mathuo/dockview#884]
**Describe the bug**
Existing tab can't be added/moved to another panel - there is no drop zone highlighted in the panel's header.

**To Reproduce**

1. Go to https://dockview.dev/demo/?theme=abyss
2. Try to add existing tab to another panel

Looks like removing `width: 100%` from `.dv-scrollable` fixes the issue

**Expected behavior**
There is should be a dropzone available to add a tab to the panel.

**Screenshots**
-

**Desktop (please complete the following information):**
 - Browser chrome 
 - Version 134.0.6998.89

**Additional context**
-

**Comment by artaommahe** [comment]
Also looks like i can't move more tabs to the panel that has multiple tabs with scrollbar (after fixing width on dv-scrollable) - there are dropzones, but dropping a tab doesn't move it there

**Comment by artaommahe** [comment]
Is there a way to disable dockview's scrollbar? Looks like it's a custom js implementation and we already have a proper working scrollbar with regular css that we can't use with the new version due to dockview's scrollbar behaviour. Btw it looks like this a works fine with touchpad.

https://github.com/user-attachments/assets/6db53228-a0c4-4773-9dda-65e026761a22

**Comment by mathuo** [comment]
Fixed in 4.2.0

- You can now use `scrollbars={"native"}` to ensure the header tabs use native scrollbar functionality
- The group dnd CSS bug is also fixed

**Comment by artaommahe** [comment]
@mathuo now it's possible to move tabs between panels but only if there is an empty space available as a drop zone. Still can't move if there are too much tabs (see video)

https://github.com/user-attachments/assets/d7926c37-7e4b-4856-944c-245dd9e2e729

**Comment by mathuo** [comment]
Apologies, fixed in 4.2.1. There was some internal refactoring in v4 related to dnd behaviours and this one must have slipped through the net.
