### ISSUE TITLE
First tab does not drag-drop when there is not enough space above the dockview area

### ISSUE THREAD

**Issue by nilsm** [mathuo/dockview#891]
**Describe the bug**
When there is not enough space above the dockview container div, the first tab does not drag/drop.

**To Reproduce**

1. Go to https://dockview.dev/templates/dockview/basic/typescript/index.html
2. Go to 'Inspect' in the developer tools
3. Set 'display: none' as the style for the header
4. Try to drag Panel 1 - it won't drag anymore
5. Drag Panel 2 into the first position - it won't drag anymore but Panel 1 can now be dragged

The same behaviour happens when there is no other div above the dockview container div - eg. for full-screen layouts where dockview is the only element on the page.

**Desktop (please complete the following information):**
 - Browser: seems to be universal but mostly tested in Chrome v134.0.6998
 - (also seen on Windows Chrome, Windows Edge, OSX Safari)

**Comment by nilsm** [comment]
More info:
1. It seems to be possible to drag the first panel by placing the mouse a little below the title
2. Even with the header visible the first panel is not draggable if the header height is < 10px approximately

**Comment by mathuo** [comment]
Which element are you setting `display: none` on?

**Comment by yanyinqing** [comment]
> Which element are you setting on?`display: none`

I have the same problem, which happens when the panel fills the whole interface.

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/c54943e8-b3cf-4960-a96d-fe5ae926a009" />

**Comment by yanyinqing** [comment]
> > Which element are you setting on?`display: none`
> 
> I have the same problem, which happens when the panel fills the whole interface.
> 
> <img alt="Image" width="1512" src="https://private-user-images.githubusercontent.com/76729473/433634387-c54943e8-b3cf-4960-a96d-fe5ae926a009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ2ODUxNzEsIm5iZiI6MTc0NDY4NDg3MSwicGF0aCI6Ii83NjcyOTQ3My80MzM2MzQzODctYzU0OTQzZTgtYjNjZi00OTYwLWE5NmQtZmU1YWU5MjZhMDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE1VDAyNDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZmRjMjJiODE1NjBmNzE2Yzc3YjBiNDkxNTExMzViZGI5NTA0OTRlMTAxYzE0NTIzOWQyMjBmM2I3YjZhNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FRFVpuouDJI2mcUMBqgWMyVxVBBBnCp6pVPnX6PCakc">

<img width="1510" alt="Image" src="https://github.com/user-attachments/assets/6b44bdb0-2cd4-4f9f-8646-823ad6fc4e07" />The first one can't be dragged. You can reproduce this problem by using "display:none" for the first div-header in the link given by the post owner.

**Comment by mathuo** [comment]
Fixed in `4.2.5`

**Comment by Lypsilonx** [comment]
This seems to not be fixed yet... I can still reproduce OPs problem

**Comment by Lypsilonx** [comment]
There seems to be some kind of deadzone blocking interactions on the top
